/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BPopover: typeof import('bootstrap-vue-next')['BPopover']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Row: typeof import('./src/components/Row.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
